---

- name: Service file
  template:
    src: nomad.service.j2
    dest: /etc/systemd/system/nomad.service
    owner: root
    group: root
    mode: "0644"
  notify: nomad restart

- name: Enable service
  systemd:
    name: nomad
    enabled: yes
    daemon_reload: yes
  when: nomad_start_at_boot

# vi:ts=2:sw=2:et:ft=yaml
