# vi:ts=2:sw=2:et:ft=yaml
---

- name: nomad service
  systemd:
    name: nomad
    daemon_reload: yes

- name: nomad start
  systemd:
    name: nomad
    state: started
  when: nomad_started

- name: nomad restart
  systemd:
    name: nomad
    state: restarted
  when: nomad_started

- name: nomad stop
  systemd:
    name: nomad
    state: stopped

